version: "3.7"

services:
  web:
    build: .
    volumes:
      - .:/code
    tty: true
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres
    ports: 
        - "5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
